// AI Event Architect - Export Module (AI-Generated Professional PDF Reports)

import { Utils } from './utils.js';
import { planner } from './planner.js';
import { uiManager } from './ui.js';

export class ExportManager {
    constructor() {
        this.aiReport = null;
        this.init();
    }

    init() {
        this.setupExportPanel();
        this.setupEventListeners();

        // Listen for panel shown event
        document.addEventListener('panelShown', (e) => {
            if (e.detail.panelId === 'export') {
                this.generateAIReport();
            }
        });
    }

    setupExportPanel() {
        const container = document.getElementById('export-content');
        if (!container) return;

        container.innerHTML = `
            <div class="d-flex justify-content-between align-items-center mb-4">
                <h3>AI-Generated Event Report</h3>
                <div class="d-flex gap-2">
                    <button class="btn btn-primary" id="regenerate-report">
                        <i class="fas fa-sync me-2"></i>Regenerate Report
                    </button>
                    <button class="btn btn-success" id="generate-pdf">
                        <i class="fas fa-file-pdf me-2"></i>Export PDF
                    </button>
                </div>
            </div>

            <div class="row">
                <div class="col-md-8">
                    <div class="card">
                        <div class="card-header d-flex justify-content-between align-items-center">
                            <h5 class="mb-0">AI Report Preview</h5>
                            <div id="report-status" class="text-muted small">Generating report...</div>
                        </div>
                        <div class="card-body">
                            <div id="report-preview" class="report-preview">
                                <div class="text-center text-muted">
                                    <i class="fas fa-robot fa-3x mb-3"></i>
                                    <p>AI is analyzing your event data and generating a comprehensive report...</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="card">
                        <div class="card-header">
                            <h5 class="mb-0">Report Options</h5>
                        </div>
                        <div class="card-body">
                            <div class="mb-3">
                                <label for="report-title" class="form-label">Report Title</label>
                                <input type="text" class="form-control" id="report-title" value="Comprehensive Event Analysis Report">
                            </div>
                            <div class="mb-3">
                                <label for="generated-by" class="form-label">Generated By</label>
                                <input type="text" class="form-control" id="generated-by" value="AI Event Architect">
                            </div>
                            <div class="mb-3">
                                <label for="report-tone" class="form-label">Report Tone</label>
                                <select class="form-select" id="report-tone">
                                    <option value="professional">Professional</option>
                                    <option value="casual">Casual</option>
                                    <option value="formal">Formal</option>
                                </select>
                            </div>
                            <div class="form-check mb-3">
                                <input class="form-check-input" type="checkbox" id="include-recommendations" checked>
                                <label class="form-check-label" for="include-recommendations">
                                    Include AI Recommendations
                                </label>
                            </div>
                            <div class="form-check mb-3">
                                <input class="form-check-input" type="checkbox" id="include-risks" checked>
                                <label class="form-check-label" for="include-risks">
                                    Include Risk Assessment
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        `;

        this.generateAIReport();
    }

    setupEventListeners() {
        document.getElementById('regenerate-report')?.addEventListener('click', () => {
            this.generateAIReport();
        });

        document.getElementById('generate-pdf')?.addEventListener('click', () => {
            this.generatePDF();
        });
    }

    async generateAIReport() {
        const statusEl = document.getElementById('report-status');
        const previewEl = document.getElementById('report-preview');

        statusEl.textContent = 'Analyzing event data...';
        previewEl.innerHTML = `
            <div class="text-center text-muted">
                <div class="spinner-border text-primary mb-3" role="status">
                    <span class="visually-hidden">Loading...</span>
                </div>
                <p>AI is analyzing your complete event planning data...</p>
            </div>
        `;

        try {
            // Check if planner is available
            if (!planner || !planner.eventState) {
                console.warn('Planner not available, using mock report');
                return this.generateMockReport();
            }

            // Gather all event data
            const eventData = {
                basics: planner.eventState.basics,
                budget: planner.eventState.budget,
                schedule: planner.eventState.schedule,
                tasks: planner.eventState.checklist,
                vendors: planner.eventState.vendors
            };

            // Call AI to generate comprehensive report
            const response = await fetch('/ai/report', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    eventData: eventData,
                    options: this.getReportOptions()
                })
            });

            if (!response.ok) {
                throw new Error('Failed to generate AI report');
            }

            const result = await response.json();
            this.aiReport = result.data;

            this.renderReportPreview();
            statusEl.textContent = 'Report generated successfully';

        } catch (error) {
            console.error('AI report generation failed:', error);
            
            // Provide fallback mock report
            this.aiReport = this.generateMockReport(eventData);
            this.renderReportPreview();
            statusEl.textContent = 'Report generated (offline mode)';
            
            // Show warning about offline mode
            previewEl.insertAdjacentHTML('afterbegin', `
                <div class="alert alert-warning">
                    <i class="fas fa-info-circle"></i> AI report generated in offline mode. Connect to internet for enhanced AI analysis.
                </div>
            `);
        }
    }

    getReportOptions() {
        return {
            title: document.getElementById('report-title')?.value || 'Comprehensive Event Analysis Report',
            generatedBy: document.getElementById('generated-by')?.value || 'AI Event Architect',
            tone: document.getElementById('report-tone')?.value || 'professional',
            includeRecommendations: document.getElementById('include-recommendations')?.checked || false,
            includeRisks: document.getElementById('include-risks')?.checked || false
        };
    }

    generateMockReport(eventData) {
        const basics = eventData.basics || {};
        const budget = eventData.budget || {};
        const schedule = eventData.schedule || [];
        const tasks = eventData.tasks || [];
        const vendors = eventData.vendors || [];

        return {
            html: `
                <div class="ai-report">
                    <div class="report-header">
                        <h2>Event Analysis Report</h2>
                        <p class="report-meta">Generated: ${new Date().toLocaleDateString()}</p>
                    </div>
                    
                    <div class="report-section">
                        <h3>📊 Event Overview</h3>
                        <p><strong>Event:</strong> ${basics.title || 'Untitled Event'}</p>
                        <p><strong>Date:</strong> ${basics.date || 'Not specified'}</p>
                        <p><strong>Guests:</strong> ${basics.guests || 0}</p>
                        <p><strong>Budget:</strong> $${budget.total || 0}</p>
                    </div>
                    
                    <div class="report-section">
                        <h3>📅 Schedule Summary</h3>
                        <p>${schedule.length} scheduled activities</p>
                        <ul>
                            ${schedule.slice(0, 3).map(item => `<li>${item.time || ''} - ${item.activity || item.title || 'Activity'}</li>`).join('')}
                        </ul>
                    </div>
                    
                    <div class="report-section">
                        <h3>✅ Tasks Progress</h3>
                        <p>${tasks.filter(t => t.completed).length}/${tasks.length} tasks completed</p>
                    </div>
                    
                    <div class="report-section">
                        <h3>🏢 Vendor Coordination</h3>
                        <p>${vendors.length} vendors engaged</p>
                    </div>
                    
                    <div class="report-section">
                        <h3>💡 Recommendations</h3>
                        <ul>
                            <li>Monitor budget allocation across categories</li>
                            <li>Ensure timely vendor confirmations</li>
                            <li>Track task completion progress</li>
                            <li>Review schedule for potential conflicts</li>
                        </ul>
                    </div>
                </div>
            `,
            summary: 'Mock report generated successfully'
        };
    }

    renderReportPreview() {
        if (!this.aiReport) return;

        const previewEl = document.getElementById('report-preview');
        previewEl.innerHTML = this.aiReport.html;
    }

    async generatePDF() {
        if (!this.aiReport) {
            Utils.showToast('Please generate a report first', 'warning');
            return;
        }

        try {
            Utils.showToast('Generating PDF report...', 'info');

            // Check if jsPDF and html2canvas are available
            if (typeof jspdf === 'undefined' || typeof html2canvas === 'undefined') {
                Utils.showToast('PDF libraries not loaded. Please check your internet connection.', 'error');
                return;
            }

            const options = this.getReportOptions();

            // Create new PDF
            const pdf = new jspdf.jsPDF('p', 'mm', 'a4');
            const pageWidth = pdf.internal.pageSize.getWidth();
            const pageHeight = pdf.internal.pageSize.getHeight();

            // Add title page
            pdf.setFontSize(24);
            pdf.text(options.title, pageWidth / 2, 40, { align: 'center' });

            pdf.setFontSize(16);
            pdf.text('AI-Generated Event Analysis', pageWidth / 2, 60, { align: 'center' });

            pdf.setFontSize(12);
            pdf.text(`Generated by ${options.generatedBy}`, pageWidth / 2, 80, { align: 'center' });
            pdf.text(`Report Date: ${new Date().toLocaleDateString()}`, pageWidth / 2, 90, { align: 'center' });

            // Add report content
            if (this.aiReport.sections) {
                let yPosition = 110;

                this.aiReport.sections.forEach(section => {
                    if (yPosition > 250) {
                        pdf.addPage();
                        yPosition = 20;
                    }

                    pdf.setFontSize(16);
                    pdf.text(section.title, 20, yPosition);
                    yPosition += 15;

                    pdf.setFontSize(11);
                    const lines = pdf.splitTextToSize(section.content, pageWidth - 40);
                    lines.forEach(line => {
                        if (yPosition > 270) {
                            pdf.addPage();
                            yPosition = 20;
                        }
                        pdf.text(line, 20, yPosition);
                        yPosition += 6;
                    });

                    yPosition += 10;
                });
            }

            // Save the PDF
            const fileName = `${options.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_${new Date().toISOString().split('T')[0]}.pdf`;
            pdf.save(fileName);

            Utils.showToast('AI-generated PDF report exported successfully!', 'success');

        } catch (error) {
            console.error('PDF generation error:', error);
            Utils.showToast('Error generating PDF. Please try again.', 'error');
        }
    }
}

// Global instance
export const exportManager = new ExportManager();
